### ISSUE TITLE
阿里云服务器无法访问

### ISSUE THREAD

**Issue by zynowhere** [rev1si0n/another-tmp-mailbox#2]
容器日志

[I 220704 13:22:17 smtp:399] Available AUTH mechanisms: LOGIN(builtin) PLAIN(builtin)
[I 220704 13:22:17 smtp:511] Peer: ('127.0.0.1', 32984)
[I 220704 13:22:17 smtp:591] ('127.0.0.1', 32984) handling connection
[I 220704 13:22:17 smtp:531] ('127.0.0.1', 32984) EOF received
[I 220704 13:22:17 smtp:733] ('127.0.0.1', 32984) Connection lost during _handle_client()
[I 220704 13:22:17 smtp:517] ('127.0.0.1', 32984) connection lost

**Comment by rev1si0n** [comment]
你尝试安装 netcat 命令，然后从本机或者其他外网服务器（telnet 命令连 25 应该也行）
```bash
nc IP 25
```
随便输几个字母按下回车，看看是否有回显，同时看看服务器那端的 docker logs 是否有输出。
确定一下端口没问题。
