### ISSUE TITLE
How to use multiple different domain names as email addresses

### ISSUE THREAD

**Issue by zhenzi0322** [rev1si0n/another-tmp-mailbox#6]

**Comment by rev1si0n** [comment]
自行修改参数
https://github.com/rev1si0n/another-tmp-mailbox/blob/master/main.py#L243
改为
```python
define("domain", multiple=True, type=str)
```
以及
https://github.com/rev1si0n/another-tmp-mailbox/blob/master/main.py#L275C5-L275C25
修改为
```python
SmtpdHandler.domains.extend(options.domain)
```

启动参数使用
```bash
-domain=a.com,b.com,c.com
```

未经测试，你可以在测试后提交 pull 请求。

**Comment by zhenzi0322** [comment]
好的

**Comment by zhenzi0322** [comment]
还有就是我收到一些临时邮件是乱码的。如下：

![image](https://github.com/rev1si0n/another-tmp-mailbox/assets/34839719/7d2638dc-88b0-4c2d-85b9-428ba018c7c6)

**Comment by zhenzi0322** [comment]
我部署了一个`denghongcai/forsaken-mail`，这个收到的码不是乱码，而我们这边收到的是乱码

**Comment by rev1si0n** [comment]
这个，应该是字符集问题导致前端显示乱码，方便的话，请将包含这封邮件的 db 数据库发到这里。

**Comment by zhenzi0322** [comment]
那个我已经解决了，谢谢了。

**Comment by itq5** [comment]
![image](https://github.com/rev1si0n/another-tmp-mailbox/assets/42521985/89d9931d-aca0-42a0-aa06-56e3a8c759a4)
多域名设置，前端是乱码的

**Comment by rev1si0n** [comment]
> ![image](https://private-user-images.githubusercontent.com/42521985/305678978-89d9931d-aca0-42a0-aa06-56e3a8c759a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMjQzNTcsIm5iZiI6MTcwODMyNDA1NywicGF0aCI6Ii80MjUyMTk4NS8zMDU2Nzg5NzgtODlkOTkzMWQtYWNhMC00MmEwLWFhMDYtNTZlM2E4Yzc1OWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA2MjczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3N2RkNDMwM2U4NDBmOWM1NjM2ODkxYTEyMzgyY2MxOWMyMTc0NDc4MjcxNTQ3Zjk1ZDYzNzgzMzUyOGY3OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2RFCimJawrBymEAWqPN0vnNK9ah69t7KyiSCacOst6U) 多域名设置，前端是乱码的

目前版本只支持单域名
